name: how_much_did_i_just_eat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  dio: ^4.0.5
  fluttertoast: ^8.0.9
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  uses-material-design: true
